# Generated by Django 4.2.1 on 2023-05-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='property_limit',
            field=models.IntegerField(default=0),
        ),
    ]
