# Generated by Django 4.2.1 on 2023-05-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accounttype_property_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('property_limit', models.IntegerField(default=0)),
                ('repost_limit', models.IntegerField(default=0)),
                ('featured_limit', models.IntegerField(default=0)),
                ('property_period', models.IntegerField(default=0)),
                ('valid_for', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='property_limit',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.package'),
        ),
    ]
