# Generated by Django 4.2.1 on 2023-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_invoice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
    ]
