# Generated by Django 4.2.1 on 2023-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_package_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_active',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
