# Generated by Django 4.2.1 on 2023-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_package_is_active_advertiser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invoices',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='invoices',
            field=models.ManyToManyField(blank=True, to='users.invoice'),
        ),
    ]
