# Generated by Django 4.2.1 on 2023-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_email_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
