# Generated by Django 4.2.1 on 2023-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_advertiser_package_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='package_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
