# Generated by Django 4.2.1 on 2023-05-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakan', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
