# Generated by Django 4.2.1 on 2023-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakan', '0003_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, to='sakan.image'),
        ),
    ]
