# Generated by Django 4.2.1 on 2023-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakan', '0005_alter_property_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='feature', to='sakan.feature'),
        ),
    ]
