# Generated by Django 4.2.1 on 2023-06-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakan', '0009_feature_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
