# Generated by Django 4.2.1 on 2023-07-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sakan', '0011_property_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('en_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visitors', models.IntegerField(default=0)),
                ('show_number', models.IntegerField(default=0)),
                ('call_number', models.IntegerField(default=0)),
                ('whatsapp_number', models.IntegerField(default=0)),
                ('sms_messages', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sakan.status')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='statistics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sakan.statistic'),
        ),
    ]
