# Generated by Django 4.2.1 on 2023-07-04 07:50

from django.db import migrations, models
import django.db.models.deletion
import sakan.models


class Migration(migrations.Migration):

    dependencies = [
        ('sakan', '0012_status_statistic_property_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='status',
            field=models.ForeignKey(blank=True, default=sakan.models.Status.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, to='sakan.status'),
        ),
    ]
